# docker-compose.yml

services:
  db:
    # 使用官方的 Postgres 镜像
    image: postgres:15
    # 如果服务重启，会自动重启容器
    restart: always
    # 设置数据库的环境变量 (密码请务必换成您自己的)
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: crm_dev
    # 将容器的 5432 端口映射到您电脑的 5432 端口
    ports:
      - '5432:5432'
    # 创建一个数据卷，确保即使容器被删除，数据库的数据也能保留下来
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
